
project_id = "uoeshejtkzngnqxtqtbl"

[functions.generate-whatsapp-code]
verify_jwt = true

[functions.unlink-whatsapp]
verify_jwt = true

[functions.auth-google-exchange]
verify_jwt = false

[functions.save-google-tokens]
verify_jwt = true
